### ISSUE TITLE
Releasing 1.0.2 in liew of PR #5 (phantomjs stack trace fix)

### ISSUE THREAD

**Issue by mastercactapus** [chaijs/assertion-error#6]
I've been seeing this come up a few times recently; any chance we could get a patch release published with the fix?

**Comment by drummerboof** [comment]
👍 This would be very handy

**Comment by meeber** [comment]
@keithamus Any objections to patch releasing this?

**Comment by rayd** [comment]
Please :smiley:

**Comment by keithamus** [comment]
Published as `1.0.2`. Let us know if there are any issues please 😄

**Comment by keithamus** [comment]
FYI @meeber it is on my todo list to ensure all of these modules auto publish whenever there are commits to master, just like `check-error` and `type-detect` now do.
